// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "fiber@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/dashboard": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get status of all market offers, orders, and balance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get status of all market",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT \u003ctoken\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "dashboard",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.DashboardResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "500": {
                        "description": "Bad server",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    }
                }
            }
        },
        "/admin/orders/{id}": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update the status of a specific order by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update status of a specific order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "JWT \u003ctoken\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Order Status",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.UpdateOrderStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.UpdateOrderStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "500": {
                        "description": "Bad server",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    }
                }
            }
        },
        "/auth/addoffer": {
            "post": {
                "description": "Add a new offer to the available offers list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Add a new offer",
                "parameters": [
                    {
                        "description": "Offer",
                        "name": "offer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Offer"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Offer added",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    }
                }
            }
        },
        "/auth/checkout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Buy a list of orders.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Checkout",
                "parameters": [
                    {
                        "description": "Checkout Request",
                        "name": "checkout",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.CheckoutRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "JWT \u003ctoken\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.CheckoutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "500": {
                        "description": "Bad server",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login a user with the given credentials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login a user",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JWT token",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "500": {
                        "description": "Bad server",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    }
                }
            }
        },
        "/auth/offers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all available offers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get available offers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT \u003ctoken\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "offers",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.OffersResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "500": {
                        "description": "Bad server",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    }
                }
            }
        },
        "/auth/orders/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the status of a specific order by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get status of a specific order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "JWT \u003ctoken\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.OrderStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "500": {
                        "description": "Bad server",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user with the given details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User added",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    },
                    "500": {
                        "description": "Bad server",
                        "schema": {
                            "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.CheckoutMessage": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.CheckoutRequest": {
            "type": "object",
            "properties": {
                "orderItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.OrderItemRequest"
                    }
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.CheckoutResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.CheckoutMessage"
                },
                "order_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.DashboardData": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "offers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Offer"
                    }
                },
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Order"
                    }
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.DashboardResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.DashboardData"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.LoginResponse": {
            "type": "object",
            "properties": {
                "auth": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.Offer": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "food"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "meat"
                },
                "price": {
                    "type": "integer",
                    "example": 100
                },
                "quantity": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.OffersResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Offer"
                    }
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.Order": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "orderItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.OrderItem"
                    }
                },
                "status": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.OrderItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "orderID": {
                    "type": "integer",
                    "example": 1
                },
                "price": {
                    "type": "integer",
                    "example": 100
                },
                "productID": {
                    "type": "integer",
                    "example": 1
                },
                "quantity": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.OrderItemRequest": {
            "type": "object",
            "properties": {
                "productID": {
                    "type": "integer",
                    "example": 1
                },
                "quantity": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.OrderStatus": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.OrderStatusResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "order": {
                    "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.Order"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.UpdateOrderStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.UpdateOrderStatusResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "$ref": "#/definitions/github_com_ICOMP-UNC_newworld-manugcr_internal_models.OrderStatus"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.UserLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "github_com_ICOMP-UNC_newworld-manugcr_internal_models.UserRegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Fiber Example API",
	Description:      "This is a sample Swagger for Fiber",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
